"""restructure chapters: heard, content_html, footnotes

Revision ID: dde0f8b3e1e4
Revises: 0e23aa47a8dd
Create Date: 2026-09-01 22:24:04.071306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde0f8b3e1e4'
down_revision: Union[str, Sequence[str], None] = '0e23aa47a8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('heard', sa.String(length=500), nullable=True))
    op.add_column('chapters', sa.Column('content_html', sa.Text(), nullable=False))
    op.add_column('chapters', sa.Column('footnotes', sa.JSON(), nullable=True))
    op.drop_column('chapters', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('chapters', 'footnotes')
    op.drop_column('chapters', 'content_html')
    op.drop_column('chapters', 'heard')
    # ### end Alembic commands ###
